language: cpp
compiler:
  - gcc
script:
  - sudo apt-get install libcppunit-dev libboost-test-dev
  - cd igloo
  - make clean compile test
  - cd ../cppunit
  - make clean compile test
  - cd ../boost.test
  - make clean compile test
  - cd ../catch
  - make clean compile test
